/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Poppins', 'sans-serif'],
      },
      // Custom responsive sizing based on viewport
      spacing: {
        '1vh': '1vh',
        '2vh': '2vh',
        '3vh': '3vh',
        '4vh': '4vh',
        '5vh': '5vh',
        '6vh': '6vh',
        '8vh': '8vh',
        '10vh': '10vh',
        '15vh': '15vh',
        '18vh': '18vh',
        '20vh': '20vh',
        '25vh': '25vh',
        '30vh': '30vh',
        '40vh': '40vh',
        '50vh': '50vh',
        '60vh': '60vh',
        '70vh': '70vh',
        '75vh': '75vh',
        '80vh': '80vh',
        '90vh': '90vh',
        '1vw': '1vw',
        '2vw': '2vw',
        '3vw': '3vw',
        '4vw': '4vw',
        '5vw': '5vw',
        '6vw': '6vw',
        '8vw': '8vw',
        '10vw': '10vw',
      },
      fontSize: {
        '0.8vw': '0.8vw',
        '0.9vw': '0.9vw',
        '1vw': '1vw',
        '1.2vw': '1.2vw',
        '1.5vw': '1.5vw',
        '1.8vw': '1.8vw',
        '2vw': '2vw',
        '2.5vw': '2.5vw',
        '3vw': '3vw',
        '1.2vh': '1.2vh',
        '1.5vh': '1.5vh',
        '1.8vh': '1.8vh',
        '2vh': '2vh',
        '2.5vh': '2.5vh',
        '3vh': '3vh',
      },
      gap: {
        '1vh': '1vh',
        '2vh': '2vh',
        '3vh': '3vh',
        '4vh': '4vh',
        '5vh': '5vh',
        '1vw': '1vw',
        '2vw': '2vw',
        '3vw': '3vw',
        '4vw': '4vw',
        '5vw': '5vw',
        '6vw': '6vw',
      },
      width: {
        '5vh': '5vh',
        '10vh': '10vh',
        '2vw': '2vw',
      },
      height: {
        '5vh': '5vh',
        '10vh': '10vh',
        '2vh': '2vh',
      },
      padding: {
        '8vw': '8vw',
        '3vw': '3vw',
        '5vw': '5vw',
        '20vh': '20vh',
      },
      minHeight: {
        '4vh': '4vh',
      },
    },
  },
  plugins: [],
};