import { Audio, Pdf, ContactCard, ImageMessage } from 'components/steps/AIWorkerStep/ChatMediaComponents';
import corollaImage from 'assets/images/worker/chat/corolla-xei-22.png';

export type ChatMessage = {
    sender: string;
    content: string | React.ReactNode;
    time: string;
    type: 'sent' | 'received';
    isContactCard?: boolean;
  }

export const chatsByWorkerAndIndustry: Record<string, Record<string, ChatMessage[]>> = {
    bruno: {
        realEstate: [
            { sender: 'Bruno', content: 'Hola, Tomás! Soy Bruno, de Darwin. 🏢', time: '14:37', type: 'sent' },
            { sender: 'Bruno', content: 'Sigues interesado en un departamento de un dormitorio cerca de Belgrano? Tenemos un nuevo proyecto que coincide con tu búsqueda anterior (con pileta y gimnasio). 🏊‍♂️🏋️‍♀️', time: '14:37', type: 'sent' },
            { sender: 'Tomás', content: <Audio />, time: '14:38', type: 'received' },
            { sender: 'Bruno', content: 'Claro! Aquí tienes el PDF con todos los detalles:', time: '14:39', type: 'sent' },
            { sender: 'Bruno', content: <Pdf description="Proyecto Tonga" worker="Bruno" industry="realEstate" />, time: '14:39', type: 'sent' },
            { sender: 'Bruno', content: 'Te gustaría agendar una visita?', time: '14:39', type: 'sent' },
            { sender: 'Tomás', content: 'Sí, me gustaría visitar. Cuándo podríamos coordinar?', time: '14:40', type: 'received' },
            { sender: 'Bruno', content: 'Tengo disponibilidad mañana a las 13:00 hs. Te sirve ese horario? 🗓️🕐', time: '14:41', type: 'sent' },
            { sender: 'Tomás', content: 'Mañana a las 13:00 está perfecto!', time: '14:42', type: 'received' },
            { sender: 'Bruno', content: 'Excelente! Ignacio te recibirá para la visita mañana.', time: '14:43', type: 'sent' },
            { sender: 'Bruno', content: <ContactCard name="Ignacio Lopez" time="14:43" type="sent"/>, time: '14:43', type: 'sent', isContactCard: true },
            { sender: 'Bruno', content: 'Podrías compartirme tu dirección de correo electrónico para enviarte un recordatorio? 📧', time: '14:43', type: 'sent' },
            { sender: 'Tomás', content: 'Tomas@gmail.com', time: '14:44', type: 'received' },
            { sender: 'Bruno', content: 'Invitación enviada a tu calendario de Google! ✅ Te enviaré un recordatorio una hora antes de tu visita. Hasta mañana! 👋✨', time: '14:45', type: 'sent' }
          ],
        automotive: [
          { sender: 'Bruno', content: 'Hola, Tomás! Soy Bruno, de Darwin.', time: '14:37', type: 'sent' },
          { sender: 'Bruno', content: '¿Seguís buscando un Toyota usado? Nos acaba de ingresar un Toyota Corolla 2022.', time: '14:37', type: 'sent' },
          { sender: 'Tomás', content: <Audio />, time: '14:38', type: 'received' },
          { sender: 'Bruno', content: 'Por supuesto! Es un Toyota Corolla XEI 2022, con 30.000 km y mantenimiento al día.', time: '14:39', type: 'sent' },
          { sender: 'Bruno', content: 'Aquí te comparto el PDF con toda la información relevante: especificaciones, precio y opciones de financiación.', time: '14:39', type: 'sent' },
          { sender: 'Bruno', content: <Pdf description="Toyota_Corolla_2022_Info.pdf" worker="Bruno" industry="automotive" />, time: '14:39', type: 'sent' },
          { sender: 'Bruno', content: 'Y respondiendo a tu otra pregunta: contamos con planes de financiación y también podés entregar tu auto como parte de pago.', time: '14:39', type: 'sent' },
          { sender: 'Tomás', content: 'Me gusta! Me gustaría verlo en persona y hacer un test drive. ¿Para cuándo podríamos agendar una visita?', time: '14:40', type: 'received' },
          { sender: 'Bruno', content: 'Mañana a las 15:00 hs tenemos disponibilidad en nuestra sucursal de Av. Cabildo. ¿Ese horario te queda bien? 🕒', time: '14:41', type: 'sent' },
          { sender: 'Tomás', content: 'Sí, mañana a las 15 hs es perfecto!', time: '14:42', type: 'received' },
          { sender: 'Bruno', content: 'Genial! Ignacio te recibirá en la agencia mañana a las 15 hs.', time: '14:43', type: 'sent' },
          { sender: 'Bruno', content: <ContactCard name="Ignacio Lopez" time="14:43" type="sent"/>, time: '14:43', type: 'sent', isContactCard: true },
          { sender: 'Bruno', content: '¿Podrías compartirme tu e-mail para enviarte el recordatorio y los detalles de la visita? 📧', time: '14:43', type: 'sent' },
          { sender: 'Tomás', content: 'Tomás@gmail.com', time: '14:44', type: 'received' },
          { sender: 'Bruno', content: 'Invitación enviada! Te mandaré un recordatorio una hora antes de la cita.', time: '14:45', type: 'sent' },
          { sender: 'Bruno', content: 'Nos vemos mañana! 🚗💨', time: '14:45', type: 'sent' }
        ],
        education: [
          { sender: 'Bruno', content: 'Hola, Tomás! Soy Bruno, de Darwin Academy.', time: '14:37', type: 'sent' },
          { sender: 'Bruno', content: 'Hace un tiempo estuviste interesado en nuestro curso de Negociación, y quería avisarte que la semana que viene lo estamos lanzando nuevamente. Estás interesado?', time: '14:37', type: 'sent' },
          { sender: 'Tomás', content: <Audio />, time: '14:38', type: 'received' },
          { sender: 'Bruno', content: 'Genial! Te comparto el programa detallado del curso.', time: '14:39', type: 'sent' },
          { sender: 'Bruno', content: <Pdf description="Contenido del curso" worker="Bruno" industry="education" />, time: '14:39', type: 'sent' },
          { sender: 'Bruno', content: 'En este documento encontrarás los módulos, metodología y profesores.', time: '14:39', type: 'sent' },
          { sender: 'Tomás', content: 'Me interesa! ¿Cuál es el precio y dónde podría anotarme?', time: '14:40', type: 'received' },
          { sender: 'Bruno', content: 'Podés inscribirte directamente en este enlace:', time: '14:41', type: 'sent' },
          { sender: 'Bruno', content: <a className="text-[#3A58ED] hover:underline" target="_blank" rel="noopener noreferrer">https://getdarwin.ai</a>, time: '14:41', type: 'sent' },
          { sender: 'Bruno', content: 'El valor del curso es de $900, e incluye acceso a materiales exclusivos y sesiones en vivo con expertos.', time: '14:41', type: 'sent' },
          { sender: 'Tomás', content: 'Ya completé la inscripción! Gracias!', time: '14:42', type: 'received' },
          { sender: 'Bruno', content: '¡Perfecto, Tomás! 🎉', time: '14:43', type: 'sent' },
          { sender: 'Bruno', content: 'Inscripción recibida! Si surge cualquier duda antes del inicio del curso, aquí estaré para ayudarte', time: '14:43', type: 'sent' },
          { sender: 'Bruno', content: 'Nos vemos en clase! 🚀', time: '14:43', type: 'sent' }
        ],
        insurance: [
          { sender: 'Bruno', content: 'Hola, Tomás! Soy Bruno de Darwin Seguros. 😊', time: '14:37', type: 'sent' },
          { sender: 'Bruno', content: '¿Seguís buscando un plan de cobertura para tu Corolla 2022? Tenemos una nueva opción que podría interesarte acorde a lo que consultaste antes.', time: '14:37', type: 'sent' },
          { sender: 'Tomás', content: <Audio />, time: '14:38', type: 'received' },
          { sender: 'Bruno', content: 'Claro, Tomás. Te paso el PDF con todos los detalles del plan.', time: '14:39', type: 'sent' },
          { sender: 'Bruno', content: <Pdf description="Plan Todo Riesgo Corolla" worker="Bruno" industry="insurance" />, time: '14:39', type: 'sent' },
          { sender: 'Tomás', content: 'Perfecto, me gustaría una reunión para ver el tema de la prima y los beneficios. ¿Cuándo podríamos coordinar?', time: '14:40', type: 'received' },
          { sender: 'Bruno', content: 'Tengo disponibilidad mañana a las 13:00 horas. ¿Te sirve ese horario? 🗓️', time: '14:41', type: 'sent' },
          { sender: 'Tomás', content: 'Perfecto, mañana a las 13:00 me viene bien!', time: '14:42', type: 'received' },
          { sender: 'Bruno', content: 'Genial 🚗 Ignacio de nuestro equipo de ventas te recibirá mañana a las 13:00 para asesorarte mejor.', time: '14:43', type: 'sent' },
          { sender: 'Bruno', content: <ContactCard name="Ignacio" time="14:43" type="sent" />, time: '14:43', type: 'sent', isContactCard: true },
          { sender: 'Bruno', content: '¿Podrías compartirme tu e-mail para enviarte un recordatorio por correo?', time: '14:43', type: 'sent' },
          { sender: 'Tomás', content: 'Sí, tomás@gmail.com', time: '14:44', type: 'received' },
          { sender: 'Bruno', content: 'Invitación enviada! Te voy a escribir una hora antes a modo de recordatorio.', time: '14:45', type: 'sent' },
          { sender: 'Bruno', content: 'Nos vemos mañana, que tengas un buen día! ✨', time: '14:45', type: 'sent' }
        ],
        services: [
        { sender: 'Bruno', content: 'Hola, Tomás! Soy Bruno de Darwin.', time: '14:37', type: 'sent' },
        { sender: 'Bruno', content: 'Hace un tiempo te contactaste con nosotros por tu declaración de impuestos. Como se acerca la temporada fiscal, quería saber si te interesa que volvamos a encargarnos de tu declaración este año. 📅📊', time: '14:37', type: 'sent' },
        { sender: 'Tomás', content: <Audio />, time: '14:38', type: 'received' },
        { sender: 'Bruno', content: 'Por supuesto, Tomás! Aquí tenés un PDF con los detalles de nuestros planes de asesoría contable para la revisión anual de impuestos.', time: '14:39', type: 'sent' },
        { sender: 'Bruno', content: <Pdf description="Planes de Asesoría Contable" worker="Bruno" industry="services" />, time: '14:39', type: 'sent' },
        { sender: 'Tomás', content: 'Perfecto. ¿Cuándo podríamos agendar una reunión para revisarlo juntos?', time: '14:40', type: 'received' },
        { sender: 'Bruno', content: 'Tengo disponibilidad mañana a las 16:00 hs. ¿Ese horario te sirve? 🗓️🕓', time: '14:41', type: 'sent' },
        { sender: 'Tomás', content: 'Sí, mañana a esa hora está perfecto para mí.', time: '14:42', type: 'received' },
        { sender: 'Bruno', content: 'Genial! Ignacio del equipo contable te recibirá mañana a las 16:00 hs. 👨‍💼', time: '14:43', type: 'sent' },
        { sender: 'Bruno', content: <ContactCard name="Ignacio" time="14:43" type="sent" />, time: '14:43', type: 'sent', isContactCard: true },
        { sender: 'Bruno', content: '¿Podrías compartir tu e-mail para enviarte la invitación?', time: '14:43', type: 'sent' },
        { sender: 'Tomás', content: 'Claro, tomás@gmail.com', time: '14:44', type: 'received' },
        { sender: 'Bruno', content: 'Invitación enviada! Te voy a mandar un recordatorio una hora antes de la reunión. ✅', time: '14:45', type: 'sent' },
        { sender: 'Bruno', content: 'Nos vemos mañana! Que tengas un gran día! ✨', time: '14:45', type: 'sent' }
      ],
      healthcare: [
        { sender: 'Bruno', content: 'Hola, Tomás! Soy Bruno de Darwin Salud. 🩺', time: '14:37', type: 'sent' },
        { sender: 'Bruno', content: 'Hace un tiempo tuviste un tratamiento dermatológico con nosotros. ¿Te gustaría agendar tu control anual?', time: '14:37', type: 'sent' },
        { sender: 'Tomás', content: <Audio />, time: '14:38', type: 'received' },
        { sender: 'Bruno', content: 'Claro, Tomás! El costo es de $30.000. 💵', time: '14:39', type: 'sent' },
        { sender: 'Bruno', content: 'Tu consulta anterior fue con el Dr. Ruiz. ¿Querés que agendemos tu control nuevamente con él?', time: '14:39', type: 'sent' },
        { sender: 'Tomás', content: 'Perfecto, con el Dr. Ruiz está bien. ¿Cuándo podríamos agendar el turno?', time: '14:40', type: 'received' },
        { sender: 'Tomás', content: '¿También aceptan obras sociales?', time: '14:40', type: 'received' },
        { sender: 'Bruno', content: 'Sí, Tomás! Aceptamos obras sociales. Tengo registrado que tu cobertura es OSED 410, que cubre el 50% del valor de la consulta. 📑', time: '14:41', type: 'sent' },
        { sender: 'Bruno', content: 'Tenemos disponibilidad mañana a las 16:00 hs. ¿Ese horario te sirve? 🗓️🕓', time: '14:41', type: 'sent' },
        { sender: 'Tomás', content: 'Sí! Tengo OSED 410, genial.', time: '14:42', type: 'received' },
        { sender: 'Tomás', content: 'Mañana a las 16:00 hs me viene perfecto!', time: '14:42', type: 'received' },
        { sender: 'Bruno', content: 'Genial! El Dr. Ruiz te recibirá mañana a las 16:00 hs en su consultorio. 👨‍⚕️', time: '14:43', type: 'sent' },
        { sender: 'Bruno', content: 'La dirección es Calle de Luchana 20, segundo piso. 📍', time: '14:43', type: 'sent' },
        { sender: 'Tomás', content: 'Perfecto! Gracias!', time: '14:44', type: 'received' },
        { sender: 'Bruno', content: 'Gracias, Tomás! Te voy a enviar un recordatorio una hora antes del turno. ⏰', time: '14:45', type: 'sent' },
        { sender: 'Bruno', content: 'Nos vemos mañana, que tengas un buen día!', time: '14:45', type: 'sent' }
      ],
      retail: [
        { sender: 'Bruno', content: 'Hola Ana, soy Bruno de Darwin Retail. 🛋️', time: '14:37', type: 'sent' },
        { sender: 'Bruno', content: 'Hace un tiempo nos consultaste por un sillón de 4 plazas para tu living. ¿Seguís buscando esa opción?', time: '14:37', type: 'sent' },
        { sender: 'Ana', content: <Audio isMan={false} />, time: '14:38', type: 'received' },
        { sender: 'Bruno', content: 'Claro Ana, te comparto un PDF con todos los detalles del modelo Livplus.', time: '14:39', type: 'sent' },
        { sender: 'Bruno', content: <Pdf description="Sillón modelo livplus - características y precio" worker="Bruno" industry="retail" />, time: '14:39', type: 'sent' },
        { sender: 'Bruno', content: 'Si comprás hoy, podemos entregarlo el viernes para que lo disfrutes durante el fin de semana. 🚚✨ ¿Querés avanzar?', time: '14:39', type: 'sent' },
        { sender: 'Ana', content: 'Genial. ¿Se puede pagar en cuotas?', time: '14:40', type: 'received' },
        { sender: 'Bruno', content: 'Sí, ofrecemos pago en cuotas o un descuento especial si lo abonas al contado. 💳💰', time: '14:41', type: 'sent' },
        { sender: 'Bruno', content: 'Te paso el link de pago para que puedas completar la compra fácilmente.', time: '14:41', type: 'sent' },
        { sender: 'Bruno', content: <a className="text-[#3A58ED] hover:underline" target="_blank" rel="noopener noreferrer">https://pago.darwin.ai/sillon-livplus</a>, time: '14:41', type: 'sent' },
        { sender: 'Bruno', content: 'Avisame cuando lo completes así coordinamos la entrega.', time: '14:41', type: 'sent' },
        { sender: 'Ana', content: 'Listo. Acabo de hacer el pago.', time: '14:42', type: 'received' },
        { sender: 'Bruno', content: 'Pago recibido. ✅', time: '14:43', type: 'sent' },
        { sender: 'Bruno', content: 'El sillón se entregará este viernes. Si tenés alguna duda, estoy para ayudarte.', time: '14:43', type: 'sent' },
        { sender: 'Bruno', content: 'Disfrutá tu nuevo sillón. 👋✨', time: '14:43', type: 'sent' }
      ]
    },
    eva: {
        realEstate: [
          { sender: 'Eva', content: 'Hola, Tomás! Soy Eva de Darwin. 😊', time: '14:37', type: 'sent' },
          { sender: 'Eva', content: 'Vimos que recientemente visitaste uno de nuestros departamentos y nos encantaría conocer tu experiencia.', time: '14:37', type: 'sent' },
          { sender: 'Eva', content: 'En una escala del 1 al 10, ¿cómo calificarías tu visita?', time: '14:37', type: 'sent' },
          { sender: 'Tomás', content: 'Hola, Eva. Todo estuvo genial. Le daría un 9.', time: '14:38', type: 'received' },
          { sender: 'Eva', content: 'Qué bueno escucharlo, Tomás! 😃', time: '14:39', type: 'sent' },
          { sender: 'Eva', content: 'Si hay algo que podamos mejorar para que tu experiencia sea un 10, contanos. Tu opinión es muy importante para nosotros.', time: '14:39', type: 'sent' },
          { sender: 'Tomás', content: 'En general, todo estuvo perfecto. Solo me hubiese gustado que la visita fuera más tarde para ver la luz natural del departamento por la tarde.', time: '14:40', type: 'received' },
          { sender: 'Eva', content: 'Muy claro, Tomás! 🌞 Vamos a compartir tu comentario con nuestro equipo de ventas para que en futuras visitas podamos tener en cuenta esa preferencia.', time: '14:41', type: 'sent' },
          { sender: 'Eva', content: 'Gracias por ayudarnos a mejorar. ¡Esperamos que encuentres el hogar ideal con nosotros! 🏡✨', time: '14:41', type: 'sent' }
        ],
        automotive: [
          { sender: 'Eva', content: '¡Hola, Tomás! 😊 Soy Eva, de Darwin.', time: '14:37', type: 'sent' },
          { sender: 'Eva', content: 'Vimos que recientemente recibiste tu vehículo y queríamos saber cómo fue tu experiencia con la entrega. ✨', time: '14:37', type: 'sent' },
          { sender: 'Eva', content: 'En una escala del 1 al 10, ¿cómo calificarías el proceso?', time: '14:37', type: 'sent' },
          { sender: 'Tomás', content: 'Hola, Eva. Todo estuvo muy bien. Le daría un 9.', time: '14:38', type: 'received' },
          { sender: 'Eva', content: '¡Nos encanta escuchar eso, Tomás! 😃', time: '14:39', type: 'sent' },
          { sender: 'Eva', content: 'Si hay algo que podamos mejorar para que tu experiencia sea un 10, contame. Nos interesa mucho tu opinión.', time: '14:39', type: 'sent' },
          { sender: 'Tomás', content: 'En general, todo perfecto. Solo me hubiera gustado retirar el auto en un concesionario más cercano a mi domicilio.', time: '14:40', type: 'received' },
          { sender: 'Eva', content: '¡Gracias por tu comentario, Tomás! Vamos a tomar ese feedback con nuestro equipo de logística para mejorar los tiempos de entrega.', time: '14:41', type: 'sent' },
          { sender: 'Eva', content: 'Gracias por confiar en Darwin y ayudarnos a crecer! 🚗 🚀', time: '14:41', type: 'sent' }
        ],
        education: [
          { sender: 'Eva', content: 'Hola, Tomás! Soy Eva de Darwin. Vimos que recientemente completaste nuestro curso de Marketing.', time: '14:37', type: 'sent' },
          { sender: 'Eva', content: 'En una escala del 1 al 10, ¿cómo calificarías tu experiencia general?', time: '14:37', type: 'sent' },
          { sender: 'Tomás', content: 'Hola, Eva! Todo estuvo genial, le daría un 8.', time: '14:38', type: 'received' },
          { sender: 'Eva', content: 'Qué bueno escucharlo, Tomás! 😃 ¿Qué podríamos mejorar para que tu experiencia sea un 10?', time: '14:39', type: 'sent' },
          { sender: 'Tomás', content: 'Quizás incluir más ejemplos prácticos durante las clases. Eso ayudaría a aplicar los conceptos de inmediato. También dar acceso a herramientas con usuarios de prueba.', time: '14:40', type: 'received' },
          { sender: 'Eva', content: 'Excelente sugerencia! Vamos a trabajar con nuestros instructores para incluir más ejemplos prácticos. 💡', time: '14:41', type: 'sent' },
          { sender: 'Eva', content: 'Gracias por confiar en Darwin para tu desarrollo profesional. Te deseamos mucho éxito aplicando lo que aprendiste! 🚀✨', time: '14:41', type: 'sent' }
        ],
        insurance: [
          { sender: 'Eva', content: 'Hola, Tomás. Soy Eva de Darwin. Notamos que recientemente contrataste nuestra póliza de seguro para tu auto.', time: '14:37', type: 'sent' },
          { sender: 'Eva', content: 'En una escala del 1 al 10, ¿cómo calificarías la facilidad del proceso de contratación?', time: '14:37', type: 'sent' },
          { sender: 'Tomás', content: 'Hola, Eva. Fue bastante fácil, le daría un 8.', time: '14:38', type: 'received' },
          { sender: 'Eva', content: '¡Genial! Nos alegra saber que fue fácil. ¿Qué podríamos mejorar para obtener una calificación más alta?', time: '14:39', type: 'sent' },
          { sender: 'Tomás', content: 'Tal vez ofrecer más opciones de pago para elegir la que mejor se adapte a mí. Me hubiera gustado tener opciones como transferencia bancaria o incluso pagos con criptomonedas.', time: '14:40', type: 'received' },
          { sender: 'Eva', content: 'Gracias por tu comentario, Tomás. Apreciamos mucho tu sugerencia y la compartiremos con nuestro equipo para seguir mejorando nuestro servicio.', time: '14:41', type: 'sent' },
          { sender: 'Eva', content: 'Gracias por elegir a Darwin para asegurar tu auto. ¡Estamos aquí para ayudarte! 😊', time: '14:41', type: 'sent' }
        ],
        services: [
          { sender: 'Eva', content: 'Hola, Tomás! Soy Eva de Darwin. Me gustaría preguntarte sobre tu experiencia con nuestros abogados. 😊', time: '14:37', type: 'sent' },
          { sender: 'Eva', content: 'En una escala del 1 al 10, ¿cómo calificarías el servicio y el resultado que recibiste?', time: '14:37', type: 'sent' },
          { sender: 'Tomás', content: 'Hola, Eva. Fue muy bueno. Le daría un 8.', time: '14:38', type: 'received' },
          { sender: 'Eva', content: 'Nos alegra tu calificación, Tomás! 😃 Si hay algo que podríamos mejorar para que sea un 10, contanos.', time: '14:39', type: 'sent' },
          { sender: 'Tomás', content: 'Hubiera preferido que el equipo llegara un poco antes y que explicaran las cosas con un lenguaje menos técnico.', time: '14:40', type: 'received' },
          { sender: 'Eva', content: 'Gracias por tu comentario, Tomás! Compartiré tus sugerencias con nuestro equipo. ✍️', time: '14:41', type: 'sent' },
          { sender: 'Eva', content: 'Gracias por ayudarnos a mejorar. ¡Esperamos verte pronto nuevamente! ✨', time: '14:41', type: 'sent' }
        ],
        healthcare: [
          { sender: 'Eva', content: 'Hola, Tomás! Soy Eva de Darwin. Notamos que recientemente finalizaste tu tratamiento dermatológico con nosotros. 😊', time: '14:37', type: 'sent' },
          { sender: 'Eva', content: 'En una escala del 1 al 10, ¿cómo calificarías el servicio que recibiste?', time: '14:37', type: 'sent' },
          { sender: 'Tomás', content: 'Hola, Eva. Todo fue excelente, le daría un 9.', time: '14:38', type: 'received' },
          { sender: 'Eva', content: 'Nos encanta escuchar eso, Tomás! 😃', time: '14:39', type: 'sent' },
          { sender: 'Eva', content: 'Si hay algo que podamos mejorar para que tu experiencia sea un 10 perfecto, contanos. Tu opinión es muy importante para nosotros.', time: '14:39', type: 'sent' },
          { sender: 'Tomás', content: 'Tal vez podrían ofrecer turnos más temprano. A veces se me complica venir en horario de oficina.', time: '14:40', type: 'received' },
          { sender: 'Eva', content: 'Gracias por tu comentario, Tomás! ⏰ Compartiremos tu sugerencia con nuestro equipo para evaluar nuevas opciones de horarios.', time: '14:41', type: 'sent' },
          { sender: 'Eva', content: 'Gracias por confiar en Darwin para tu cuidado dermatológico. Estamos cuando nos necesites! ✨', time: '14:41', type: 'sent' }
        ],
        retail: [
          { sender: 'Eva', content: '¡Hola, Tomás! 😊 Soy Eva, del equipo de Customer Experience de Darwin.', time: '14:37', type: 'sent' },
          { sender: 'Eva', content: 'Quería saber cómo fue tu experiencia comprando tu sillón con nosotros.', time: '14:37', type: 'sent' },
          { sender: 'Eva', content: 'En una escala del 1 al 10, ¿cómo calificarías tu experiencia?', time: '14:37', type: 'sent' },
          { sender: 'Tomás', content: 'Hola, Eva. La verdad, todo estuvo muy bien. Le daría un 9.', time: '14:38', type: 'received' },
          { sender: 'Eva', content: '¡Nos encanta escuchar eso, Tomás! 😃', time: '14:39', type: 'sent' },
          { sender: 'Eva', content: 'Si hay algo que podamos mejorar para que tu próxima experiencia sea un 10, ¡contame! Nos encanta recibir tu feedback.', time: '14:39', type: 'sent' },
          { sender: 'Tomás', content: 'En general, todo perfecto. Solo me hubiera gustado que el proceso de entrega fuera un poco más rápido.', time: '14:40', type: 'received' },
          { sender: 'Eva', content: '¡Gracias por tu comentario, Tomás! Vamos a tomar ese feedback con nuestro equipo de logística para mejorar los tiempos de entrega.', time: '14:41', type: 'sent' },
          { sender: 'Eva', content: 'Gracias por confiar en Darwin y ayudarnos a crecer! 🛋️✨', time: '14:41', type: 'sent' }
        ]
    },
    sophia: {
      realEstate: [
        { sender: 'Sophia', content: 'Hola, Tomás! Soy Sophia de Darwin. 🏡', time: '14:37', type: 'sent' },
        { sender: 'Sophia', content: 'Está por cumplirse un año desde que compraste tu departamento con nosotros, y por eso estamos ofreciendo un paquete especial de chequeo anual del hogar. Además, tenemos disponible un tratamiento especial para pisos de madera. ¿Te interesaría?', time: '14:37', type: 'sent' },
        { sender: 'Tomás', content: 'Hola Sophia! ¿Qué incluye la inspección y cuál es el costo total?', time: '14:38', type: 'received' },
        { sender: 'Sophia', content: <>El chequeo anual incluye:<br /><br />🔹 Inspección de instalaciones eléctricas ⚡<br /><br />🔹 Revisión de plomería y grifería 🚰<br /><br />🔹 Evaluación del estado de las paredes 🧱</>, time: '14:39', type: 'sent' },
        { sender: 'Sophia', content: 'El costo total es de $30.', time: '14:39', type: 'sent' },
        { sender: 'Sophia', content: 'También ofrecemos un tratamiento especial para pisos de madera por un costo adicional. ¿Te interesaría incluirlo?', time: '14:39', type: 'sent' },
        { sender: 'Tomás', content: 'Estoy interesado! ¿Podemos agendar ambos servicios para el próximo martes?', time: '14:40', type: 'received' },
        { sender: 'Sophia', content: 'Sí, tenemos disponibilidad el martes a la 13:00 hs. 🗓️🕐', time: '14:41', type: 'sent' },
        { sender: 'Sophia', content: '¿Podrías compartirme tu correo electrónico para enviarte la confirmación y un recordatorio?', time: '14:41', type: 'sent' },
        { sender: 'Tomás', content: 'Claro, mi correo es tomas@gmail.com', time: '14:42', type: 'received' },
        { sender: 'Sophia', content: 'Invitación enviada! ✅', time: '14:43', type: 'sent' },
        { sender: 'Sophia', content: 'Te enviaré un recordatorio una hora antes del turno.', time: '14:43', type: 'sent' },
        { sender: 'Sophia', content: 'Que tengas un excelente día! Nos vemos pronto! ✨', time: '14:43', type: 'sent' }
      ], 
      automotive: [
        { sender: 'Sophia', content: 'Hola, Tomás! 😊 Se acerca el primer aniversario de la compra de tu auto, y queremos recordarte que es un buen momento para realizar el primer service. Te gustaría coordinar un turno para realizarlo con nosotros?', time: '14:37', type: 'sent' },
        { sender: 'Tomás', content: 'Hola Sophia! ¿Qué incluye el primer service y cuánto cuesta?', time: '14:38', type: 'received' },
        { sender: 'Sophia', content: <>El primer service incluye:<br /><br />🔹 Cambio de aceite 🛢️<br /><br />🔹 Cambio de filtros de nafta y aire 🏎️<br /><br />🔹 Alineación del auto ⚙️</>, time: '14:39', type: 'sent' },
        { sender: 'Sophia', content: 'El costo del primer service es de $100.', time: '14:39', type: 'sent' },
        { sender: 'Tomás', content: 'Perfecto. ¿Tienen disponibilidad para el martes de la próxima semana?', time: '14:40', type: 'received' },
        { sender: 'Sophia', content: 'Sí! Tenemos disponibilidad el martes a las 13hs.', time: '14:41', type: 'sent' },
        { sender: 'Sophia', content: 'Podrías darme tu e-mail para agendar el turno y enviarte la confirmación por e-mail?', time: '14:41', type: 'sent' },
        { sender: 'Tomás', content: 'Tomas@gmail.com', time: '14:42', type: 'received' },
        { sender: 'Sophia', content: 'Gracias Tomás, te envié la información por correo. Te enviaré un recordatorio una hora antes del turno.', time: '14:43', type: 'sent' },
        { sender: 'Sophia', content: '¡Gracias por confiar en nosotros, Tomás! 🚗✨', time: '14:43', type: 'sent' }
      ],
      education: [
        { sender: 'Sophia', content: 'Hola, Ana! Soy Sophia de Darwin. 😊', time: '14:37', type: 'sent' },
        { sender: 'Sophia', content: 'Hace un tiempo realizaste nuestro curso de marketing digital. Estamos lanzando un nuevo curso de Analítica y quería saber si te interesaría!', time: '14:37', type: 'sent' },
        { sender: 'Ana', content: 'Hola Sophia! Sí, podrías darme más información sobre el curso?', time: '14:38', type: 'received' },
        { sender: 'Sophia', content: 'Genial! Es un curso de cuatro módulos, donde vas a aprender a crear tableros y a interpretar métricas clave para optimizar tus campañas. 📊✨', time: '14:39', type: 'sent' },
        { sender: 'Sophia', content: 'Aquí tenés un PDF con el programa y más detalles:', time: '14:39', type: 'sent' },
        { sender: 'Sophia', content: <Pdf description="Temario curso analítica web" worker="Sophia" industry="education" />, time: '14:39', type: 'sent' },
        { sender: 'Sophia', content: '¿Te parece bien si te contacto la próxima semana para aclarar cualquier duda y ayudarte con la inscripción?', time: '14:39', type: 'sent' },
        { sender: 'Ana', content: 'Suena muy interesante! ¿Hasta cuándo hay tiempo para inscribirse?', time: '14:40', type: 'received' },
        { sender: 'Sophia', content: 'Las inscripciones cierran la semana que viene. 🗓️', time: '14:41', type: 'sent' },
        { sender: 'Sophia', content: '¿Querés que te recuerde antes del cierre?', time: '14:41', type: 'sent' },
        { sender: 'Ana', content: 'Sí, por favor.', time: '14:42', type: 'received' },
        { sender: 'Sophia', content: 'Perfecto, Ana! Te voy a escribir en unos días para recordártelo. 📅', time: '14:43', type: 'sent' },
        { sender: 'Sophia', content: 'Si tenés alguna otra duda, escribime tranquila. Estamos en contacto! 😊✨', time: '14:43', type: 'sent' }
      ],
      insurance: [
        { sender: 'Sophia', content: 'Hola, Tomás! 😊 Se acerca el primer aniversario de la compra de tu auto, y queremos recordarte que es un buen momento para revisar tu póliza de seguro. ¿Te gustaría que revisemos juntos las opciones para mejorar tu cobertura?', time: '14:37', type: 'sent' },
        { sender: 'Tomás', content: 'Hola Sophia! ¿Qué beneficios adicionales podría obtener?', time: '14:38', type: 'received' },
        { sender: 'Sophia', content: <>Podríamos incluir:<br /><br />🔹 Cobertura por granizo<br /><br />🔹 Asistencia en viaje extendida<br /><br />🔹 Reposición a nuevo en caso de robo total</>, time: '14:39', type: 'sent' },
        { sender: 'Sophia', content: 'Y lo mejor es que por ser cliente con buen historial, el incremento sería mínimo, solo un 5% adicional a tu prima actual.', time: '14:39', type: 'sent' },
        { sender: 'Tomás', content: 'Suena interesante. ¿Podríamos coordinar una llamada para la próxima semana?', time: '14:40', type: 'received' },
        { sender: 'Sophia', content: 'Sí! Tenemos disponibilidad el martes a las 14hs.', time: '14:41', type: 'sent' },
        { sender: 'Sophia', content: '¿Te gustaría que te envíe un comparativo de tu póliza actual vs la mejorada antes de la llamada?', time: '14:41', type: 'sent' },
        { sender: 'Tomás', content: 'Sí, por favor. Mi correo es Tomas@gmail.com', time: '14:42', type: 'received' },
        { sender: 'Sophia', content: 'Perfecto Tomás, acabo de enviarte el comparativo. Nos hablamos el martes a las 14hs.', time: '14:43', type: 'sent' },
        { sender: 'Sophia', content: 'Te enviaré un recordatorio una hora antes de la llamada. ¡Gracias por confiar en nosotros! 🛡️✨', time: '14:43', type: 'sent' }
      ],
      services: [
        { sender: 'Sophia', content: 'Hola, Ana! Soy Sophia de Darwin. 😊 Hace un tiempo utilizaste nuestro servicio de asesoría contable y ahora tenemos un servicio complementario de planificación fiscal para ayudarte a optimizar tus impuestos. ¿Te gustaría conocer más?', time: '14:37', type: 'sent' },
        { sender: 'Ana', content: 'Hola, Sophia. Sí, suena interesante. Contame más.', time: '14:38', type: 'received' },
        { sender: 'Sophia', content: 'El servicio de planificación fiscal te ayuda a organizar tus estados financieros y encontrar oportunidades para optimizar tus impuestos. 📈✨', time: '14:39', type: 'sent' },
        { sender: 'Sophia', content: '¿Querés que te envíe un documento con más información detallada?', time: '14:39', type: 'sent' },
        { sender: 'Ana', content: 'Sí, por favor! ¿Cuándo podríamos agendar una reunión breve para charlarlo mejor?', time: '14:40', type: 'received' },
        { sender: 'Sophia', content: <Pdf description="Servicio de planificación fiscal" worker="Sophia" industry="services" />, time: '14:39', type: 'sent' },
        { sender: 'Sophia', content: 'Tenemos disponibilidad el próximo lunes a las 16:00 hs. ¿Ese horario te sirve? 📅🕓', time: '14:41', type: 'sent' },
        { sender: 'Ana', content: 'Perfecto!', time: '14:42', type: 'received' },
        { sender: 'Sophia', content: <ContactCard name="Vermonte" time="14:43" type="sent" />, time: '14:43', type: 'sent', isContactCard: true },
        { sender: 'Sophia', content: 'Genial, Ana! Tu reunión con el Sr. Vermonte está confirmada para el lunes a las 16:00 hs. 👨‍💼📌', time: '14:43', type: 'sent' },
        { sender: 'Ana', content: 'Gracias, nos vemos el lunes!', time: '14:44', type: 'received' }
      ],
      healthcare: [
        { sender: 'Sophia', content: 'Hola, Ana! Hace un tiempo tuviste un tratamiento dermatológico con nosotros. Quería contarte que actualmente estamos ofreciendo un servicio de limpieza facial. ¿Te gustaría recibir más información? 😊', time: '14:37', type: 'sent' },
        { sender: 'Ana', content: 'Hola, Sophia. Sí, suena interesante! ¿Podrías contarme más?', time: '14:38', type: 'received' },
        { sender: 'Sophia', content: 'Por supuesto! Es un tratamiento profesional de limpieza de la piel. Aquí te dejo un PDF con todos los detalles:', time: '14:39', type: 'sent' },
        { sender: 'Sophia', content: <Pdf description="Limpieza de cutis profesional" worker="Sophia" industry="healthcare" />, time: '14:39', type: 'sent' },
        { sender: 'Sophia', content: 'Tenemos un descuento exclusivo para quienes agenden para la próxima semana.', time: '14:39', type: 'sent' },
        { sender: 'Ana', content: 'Sí, me interesa! ¿Qué disponibilidad tienen para la próxima semana?', time: '14:40', type: 'received' },
        { sender: 'Sophia', content: 'Tenemos disponibilidad el lunes a las 16:00 hs. ¿Ese horario te sirve? 🗓️🕓', time: '14:41', type: 'sent' },
        { sender: 'Ana', content: 'Sí, perfecto.', time: '14:42', type: 'received' },
        { sender: 'Sophia', content: 'Genial, Ana! Ya agendé tu turno para el lunes a las 16:00 hs. Te enviaré un recordatorio una hora antes de tu cita. ✉️✨', time: '14:43', type: 'sent' },
        { sender: 'Sophia', content: 'Nos vemos pronto!', time: '14:43', type: 'sent' }
      ],
      retail: [
        { sender: 'Sophia', content: 'Hola, Ana! Soy Sophia de Darwin Retail. 😊', time: '14:37', type: 'sent' },
        { sender: 'Sophia', content: 'Hace unas semanas compraste el sillón Livplus con nosotros. Queríamos contarte que ahora estamos ofreciendo una mesa ratona combinada con ese modelo, ideal para completar tu living. ¿Te interesaría conocer más?', time: '14:37', type: 'sent' },
        { sender: 'Ana', content: 'Hola Sophia! Sí, contame más sobre esa mesa ratona.', time: '14:38', type: 'received' },
        { sender: 'Sophia', content: 'Genial! La mesa ratona modelo Woodline combina perfecto con el Livplus. Tiene estructura de madera maciza, diseño minimalista y espacio de guardado.', time: '14:39', type: 'sent' },
        { sender: 'Sophia', content: <Pdf description="Mesa Ratona Woodline - Fotos, dimensiones y precio" worker="Sophia" industry="retail" />, time: '14:39', type: 'sent' },
        { sender: 'Sophia', content: 'Si realizás la compra hoy, podemos entregarlo junto al paquete de accesorios este viernes. 🚚✨ ¿Te gustaría avanzar?', time: '14:39', type: 'sent' },
        { sender: 'Ana', content: 'Sí, me interesa. ¿Se puede pagar en cuotas?', time: '14:40', type: 'received' },
        { sender: 'Sophia', content: 'Sí! Ofrecemos pago en cuotas o un descuento especial si abonás al contado. 💳💰', time: '14:41', type: 'sent' },
        { sender: 'Sophia', content: 'Te paso el link de pago para que puedas completar la compra fácilmente.', time: '14:41', type: 'sent' },
        { sender: 'Sophia', content: <a className="text-[#3A58ED] hover:underline" target="_blank" rel="noopener noreferrer">https://pago.darwin.ai/mesa-woodline</a>, time: '14:41', type: 'sent' },
        { sender: 'Sophia', content: 'Avisame cuando lo completes y coordinamos la entrega.', time: '14:41', type: 'sent' },
        { sender: 'Ana', content: 'Listo, acabo de hacer el pago.', time: '14:42', type: 'received' },
        { sender: 'Sophia', content: 'Perfecto, pago recibido! ✅', time: '14:43', type: 'sent' },
        { sender: 'Sophia', content: 'La mesa será entregada este viernes junto al resto del pedido. Si tenés cualquier duda, estoy acá para ayudarte.', time: '14:43', type: 'sent' },
        { sender: 'Sophia', content: 'Gracias por seguir confiando en nosotros, Ana! Que lo disfrutes! 👋✨', time: '14:43', type: 'sent' }
      ]
    },
    alba: {
      realEstate: [
        { sender: 'Tomás', content: 'Hola! Estoy buscando un departamento en Palermo, ¿me pueden ayudar?', time: '14:37', type: 'received' },
        { sender: 'Alba', content: 'Hola, Tomás! Soy Alba, de Darwin Real Estate.', time: '14:38', type: 'sent' },
        { sender: 'Alba', content: 'Claro! ¿Buscás un monoambiente, dos ambientes o algo más grande?', time: '14:38', type: 'sent' },
        { sender: 'Tomás', content: <Audio />, time: '14:39', type: 'received' },
        { sender: 'Tomás', content: 'Busco un 2 ambientes con balcón y buena ubicación. Tienen opciones de financiamiento para el pago del departamento?', time: '14:39', type: 'received' },
        { sender: 'Alba', content: 'Claro! Tenemos el departamento justo para vos. Este es un departamento de 2 ambientes, te comparto un PDF con más información del departamento y sus opciones de financiamiento.', time: '14:40', type: 'sent' },
        { sender: 'Alba', content: <Pdf description="Detalles del departamento y opciones de financiación" worker="Alba" industry="realEstate" />, time: '14:40', type: 'sent' },
        { sender: 'Alba', content: '¿Querés coordinar una visita para verlo?', time: '14:40', type: 'sent' },
        { sender: 'Tomás', content: 'Sí, ¿podría pasar mañana?', time: '14:41', type: 'received' },
        { sender: 'Alba', content: 'Tenemos disponibilidad mañana a las 15:00hs para una visita.', time: '14:42', type: 'sent' },
        { sender: 'Alba', content: '¿Podrías pasarme tu e-mail para enviarte la confirmación y el recordatorio?', time: '14:42', type: 'sent' },
        { sender: 'Tomás', content: 'Tomás@gmail.com', time: '14:43', type: 'received' },
        { sender: 'Alba', content: <ContactCard name="Ignacio" time="14:44" type="sent" />, time: '14:44', type: 'sent', isContactCard: true },
        { sender: 'Alba', content: 'Perfecto! Te recibirá Ignacio de nuestro equipo mañana a las 15hs.', time: '14:44', type: 'sent' },
        { sender: 'Alba', content: 'Te envié la invitación al correo y te escribiré una hora antes de la visita. ¡Nos vemos mañana! 🏡✨', time: '14:44', type: 'sent' }
      ],
      automotive: [
        { sender: 'Tomás', content: 'Hola! Estoy buscando un auto usado, ¿me pueden ayudar?', time: '14:37', type: 'received' },
        { sender: 'Alba', content: 'Hola, Tomás! Soy Alba, de Darwin Autos.', time: '14:38', type: 'sent' },
        { sender: 'Alba', content: 'Claro! ¿Estás buscando un sedán, SUV o hatchback?', time: '14:38', type: 'sent' },
        { sender: 'Tomás', content: <Audio />, time: '14:39', type: 'received' },
        { sender: 'Alba', content: 'Entendido! Un sedán económico y cómodo. Te comparto una opción:', time: '14:40', type: 'sent' },
        { sender: 'Alba', content: <ImageMessage src={corollaImage} alt="Car image" />, time: '14:40', type: 'sent' },
        { sender: 'Alba', content: 'Es un Toyota Corolla XEI 2022, con mantenimiento al día. ¿Querés coordinar una visita para verlo?', time: '14:40', type: 'sent' },
        { sender: 'Tomás', content: 'Sí, ¿podría pasar mañana?', time: '14:41', type: 'received' },
        { sender: 'Alba', content: 'Tenemos disponibilidad mañana a las 15:00hs para un test drive.', time: '14:42', type: 'sent' },
        { sender: 'Alba', content: 'Para ayudarte mejor, ¿te gustaría pagarlo al contado, financiado o entregar un auto como parte de pago?', time: '14:42', type: 'sent' },
        { sender: 'Tomás', content: 'Me gustaría financiarlo. ¿Cuáles son las opciones de financiamiento?', time: '14:43', type: 'received' },
        { sender: 'Alba', content: 'Aquí tienes las opciones de financiamiento:', time: '14:44', type: 'sent' },
        { sender: 'Alba', content: <Pdf description="Opciones de financiamiento" worker="Alba" industry="automotive" />, time: '14:44', type: 'sent' },
        { sender: 'Alba', content: '¿Podrías pasarme tu e-mail para enviarte la confirmación y el recordatorio?', time: '14:44', type: 'sent' },
        { sender: 'Tomás', content: 'Tomás@gmail.com', time: '14:45', type: 'received' },
        { sender: 'Alba', content: 'Perfecto! Te recibirá Ignacio de nuestro equipo mañana a las 15hs.', time: '14:46', type: 'sent' },
        { sender: 'Alba', content: <ContactCard name="Ignacio" time="14:46" type="sent" />, time: '14:46', type: 'sent', isContactCard: true },
        { sender: 'Alba', content: 'Te envié la invitación al correo y te escribiré una hora antes de la visita. Nos vemos mañana! 🚗✨', time: '14:46', type: 'sent' }
      ],
      education: [
        { sender: 'Tomás', content: '¡Hola! Estoy interesado en el curso de UX/UI. ¿Cuándo empieza?', time: '14:37', type: 'received' },
        { sender: 'Alba', content: '¡Hola, Tomás! 😊 El curso de UX/UI comienza el 15 de marzo. Es un programa intensivo diseñado para que aprendas desde los fundamentos hasta la aplicación práctica.', time: '14:38', type: 'sent' },
        { sender: 'Tomás', content: 'Genial. ¿Tenés un documento para que pueda ver los módulos y la duración del curso?', time: '14:39', type: 'received' },
        { sender: 'Alba', content: '¡Por supuesto! El curso dura 8 semanas e incluye módulos sobre diseño de interfaces, usabilidad, prototipado y herramientas como Figma. Te comparto un PDF con todos los detalles. 📄👇', time: '14:40', type: 'sent' },
        { sender: 'Alba', content: <Pdf description="Curso UX/UI 15-marzo" worker="Alba" industry="education" />, time: '14:40', type: 'sent' },
        { sender: 'Tomás', content: 'Perfecto. ¿Cuál es el precio y dónde puedo inscribirme?', time: '14:41', type: 'received' },
        { sender: 'Alba', content: 'El curso tiene un costo de $900. Puedes inscribirte directamente en el siguiente enlace:', time: '14:42', type: 'sent' },
        { sender: 'Alba', content: <a className="text-[#3A58ED] hover:underline" target="_blank" rel="noopener noreferrer">https://www.link-al-curso-UX-UI.com/inscribirse</a>, time: '14:42', type: 'sent' },
        { sender: 'Alba', content: 'Si tienes alguna otra duda, ¡aquí estoy para ayudarte! 😊', time: '14:42', type: 'sent' },
        { sender: 'Tomás', content: 'Ya completé la inscripción! Gracias!!', time: '14:43', type: 'received' },
        { sender: 'Alba', content: '¡Perfecto, Tomás! 🎉', time: '14:44', type: 'sent' },
        { sender: 'Alba', content: 'Inscripción recibida! Si surge cualquier duda antes del inicio del curso, aquí estaré para ayudarte', time: '14:44', type: 'sent' },
        { sender: 'Alba', content: 'Nos vemos en clase! 🚀', time: '14:44', type: 'sent' },
      ],
      insurance: [
        { sender: 'Ana', content: 'Hola, quisiera recibir una cotización para un seguro de auto. ¿Podrían ayudarme?', time: '14:37', type: 'received' },
        { sender: 'Alba', content: '¡Hola, Ana! Soy Alba, de Darwin Seguros. 🚗', time: '14:38', type: 'sent' },
        { sender: 'Alba', content: '¡Por supuesto! ¿Podrías decirme la marca, modelo y año de tu auto?', time: '14:38', type: 'sent' },
        { sender: 'Ana', content: <Audio isMan={false} />, time: '14:39', type: 'received' },
        { sender: 'Alba', content: '¡Entendido! Un Corolla 2022.', time: '14:40', type: 'sent' },
        { sender: 'Alba', content: '¿Preferirías una cobertura básica o algo más completo que incluya daños a terceros, robo y asistencia en ruta?', time: '14:40', type: 'sent' },
        { sender: 'Ana', content: 'Me gustaría una cobertura completa, para estar tranquila.', time: '14:41', type: 'received' },
        { sender: 'Alba', content: '¡Perfecto! Tenemos varias opciones que se ajustan a tus necesidades. Te envío aquí mismo en el chat un PDF con información detallada sobre los planes y sus beneficios. 📄', time: '14:42', type: 'sent' },
        { sender: 'Alba', content: <Pdf description="Plan Todo Riesgo Corolla" worker="Alba" industry="insurance" />, time: '14:42', type: 'sent' },
        { sender: 'Alba', content: '¿Quieres agendar una llamada para repasar estas opciones y aclarar cualquier duda?', time: '14:42', type: 'sent' },
        { sender: 'Ana', content: '¡Sí, por favor! ¿Podríamos tener la llamada mañana a las 16:00?', time: '14:43', type: 'received' },
        { sender: 'Alba', content: '¡Claro que sí! Acabo de agendar nuestra llamada para mañana a las 16:00. Te enviaré un recordatorio una hora antes. 📅', time: '14:44', type: 'sent' },
        { sender: 'Alba', content: <ContactCard name="Sara" time="14:45" type="sent" isMan={false} />, time: '14:45', type: 'sent', isContactCard: true },
        { sender: 'Alba', content: 'Hablarás con Sara de nuestro equipo. ¡Hasta mañana! 👋✨', time: '14:45', type: 'sent' },
      ],
      services: [
        { sender: 'Tomás', content: '¡Hola! Estoy buscando a un abogado para que me ayude con un tema contractual. ¿Podrían orientarme?', time: '14:37', type: 'received' },
        { sender: 'Alba', content: '¡Hola, Tomás! Soy Alba, de Darwin. 😊⚖️', time: '14:38', type: 'sent' },
        { sender: 'Alba', content: 'Claro. Para comenzar, ¿podrías contarme un poco más sobre tu situación y qué tipo de contrato necesitas? 📝', time: '14:38', type: 'sent' },
        { sender: 'Tomás', content: <Audio />, time: '14:39', type: 'received' },
        { sender: 'Alba', content: 'Perfecto! 👍', time: '14:40', type: 'sent' },
        { sender: 'Alba', content: '¿Cuál es el plazo de este contrato comercial? ¿Es algo que te gustaría resolver en la próxima semana o no tienes tanto apuro? 📅⏳', time: '14:40', type: 'sent' },
        { sender: 'Tomás', content: 'Quiero avanzar en cuanto antes. ¿Podría tener una reunión mañana?', time: '14:41', type: 'received' },
        { sender: 'Alba', content: 'Tenemos disponibilidad mañana a las 16:00 horas para una primera reunión.', time: '14:42', type: 'sent' },
        { sender: 'Alba', content: '¿Podrías pasarme tu correo electrónico para enviarte la confirmación?', time: '14:42', type: 'sent' },
        { sender: 'Tomás', content: 'Mi correo es tomas@gmail.com', time: '14:43', type: 'received' },
        { sender: 'Alba', content: '¡Invitación enviada! ✅ Mañana te reunirás con María, una de nuestras especialistas, a las 16:00 horas para resolver todas tus consultas.', time: '14:44', type: 'sent' },
        { sender: 'Alba', content: <ContactCard name="María" time="14:46" type="sent" isMan={false} />, time: '14:46', type: 'sent', isContactCard: true },
        { sender: 'Alba', content: 'Te enviaré un recordatorio una hora antes de la reunión. ¡Nos vemos pronto! 👋', time: '14:46', type: 'sent' }
      ],
      healthcare: [
        { sender: 'Ana', content: 'Hola, me gustaría programar una cita para dermatología. ¿Podrías ayudarme?', time: '14:37', type: 'received' },
        { sender: 'Alba', content: '¡Hola Ana! Soy Alba de la Clínica Dermo Darwin. 😊', time: '14:38', type: 'sent' },
        { sender: 'Alba', content: 'Por supuesto, ¿qué día prefieres?', time: '14:38', type: 'sent' },
        { sender: 'Ana', content: <Audio isMan={false} />, time: '14:39', type: 'received' },
        { sender: 'Alba', content: '¡Perfecto! 👍 Tenemos disponibilidad el próximo miércoles con el Dr. Ortiz.', time: '14:40', type: 'sent' },
        { sender: 'Alba', content: '¿Podrías contarme un poco sobre tu consulta o preocupación actual para tomar nota antes de tu visita?', time: '14:40', type: 'sent' },
        { sender: 'Ana', content: 'Tengo un sarpullido en el brazo que aparece de vez en cuando, y esta vez se ha extendido más de lo habitual. Quiero que el Dr. Ortiz lo revise.', time: '14:41', type: 'received' },
        { sender: 'Alba', content: 'Entendido. Reservaré tu cita para el miércoles a las 3:00 PM con el Dr. Ortiz. 📅🕒', time: '14:42', type: 'sent' },
        { sender: 'Alba', content: '¿Podrías proporcionarme tu correo electrónico para enviarte la confirmación y un recordatorio?', time: '14:42', type: 'sent' },
        { sender: 'Ana', content: 'Claro, es ana@gmail.com', time: '14:43', type: 'received' },
        { sender: 'Alba', content: '¡Listo! Acabo de enviarte el correo. ✅', time: '14:44', type: 'sent' },
        { sender: 'Alba', content: 'Te recordaré una hora antes de tu cita.', time: '14:44', type: 'sent' },
        { sender: 'Alba', content: 'Si tienes alguna otra pregunta, estoy aquí para ayudarte. ¡Nos vemos pronto! 👋✨', time: '14:44', type: 'sent' }
      ],
      retail: [
        { sender: 'Ana', content: 'Hola, estoy buscando un sillón para 4 personas.', time: '14:37', type: 'received' },
        { sender: 'Alba', content: '¡Hola, Ana! Soy Alba, de Darwin. ¿Podrías contarme un poco más sobre el estilo o el espacio donde irá el sillón?', time: '14:38', type: 'sent' },
        { sender: 'Ana', content: <Audio isMan={false} />, time: '14:39', type: 'received' },
        { sender: 'Alba', content: 'Para el  living, creo que este modelo puede interesarte! Te envío aquí mismo el PDF con las especificaciones y el precio.', time: '14:40', type: 'sent' },
        { sender: 'Alba', content: <Pdf description="Sillón modelo livplus" worker="Alba" industry="retail" />, time: '14:40', type: 'sent' },
        { sender: 'Alba', content: 'Ana, si realizas la compra hoy, podemos entregarlo este viernes para que puedas disfrutarlo durante el fin de semana. ¿Te gustaría avanzar?', time: '14:40', type: 'sent' },
        { sender: 'Ana', content: '¿Se puede pagar en cuotas?', time: '14:41', type: 'received' },
        { sender: 'Alba', content: '¡Sí! Ofrecemos pago en cuotas o un descuento especial si lo abonas al contado. Te envío aquí mismo un link para que puedas realizar el pago fácilmente', time: '14:42', type: 'sent' },
        { sender: 'Alba', content: <a href="#" className="text-[#3A58ED] hover:underline" target="_blank" rel="noopener noreferrer">https://www.negocio-de-sillon.com/pagar-cuota-mensual</a>, time: '14:42', type: 'sent' },
        { sender: 'Alba', content: 'Avísame cuando lo completes y coordinamos la entrega.', time: '14:42', type: 'sent' },
        { sender: 'Ana', content: 'Listo! Acabo de realizar el pago', time: '14:43', type: 'received' },
        { sender: 'Alba', content: 'recibido! ✅', time: '14:44', type: 'sent' },
        { sender: 'Alba', content: 'Te confirmo entonces que el sillón será entregado este viernes. Cualquier cosa, estoy aquí! 👋✨', time: '14:44', type: 'sent' },
        { sender: 'Alba', content: 'Que lo disfrutes!', time: '14:44', type: 'sent' },
      
      ]
    },
    lucas: {
      realEstate: [
        { sender: 'Lucas', content: '¡Hola, Tomás! 😊 Quería recordarte que esta semana venció la cuota mensual de tu departamento.', time: '14:37', type: 'sent' },
        { sender: 'Lucas', content: '¿Tenés una fecha estimada en la que podrías realizar el pago?', time: '14:37', type: 'sent' },
        { sender: 'Tomás', content: 'No creo que pueda pagar esta semana. ¿Qué pasa si me atraso en el pago?', time: '14:38', type: 'received' },
        { sender: 'Lucas', content: 'Si realizás el pago dentro de la próxima semana, podemos hacer una excepción y no aplicar intereses por el atraso.', time: '14:39', type: 'sent' },
        { sender: 'Lucas', content: 'A partir de la segunda semana de vencimiento, sí se empiezan a aplicar intereses por mora.', time: '14:39', type: 'sent' },
        { sender: 'Lucas', content: 'Es decir, tenés hasta las 18 hs del viernes de la semana siguiente, o se aplicarán intereses.', time: '14:39', type: 'sent' },
        { sender: 'Tomás', content: '¿De cuánto es la penalización?', time: '14:40', type: 'received' },
        { sender: 'Lucas', content: 'A partir de la segunda semana de vencimiento, aplica un interés diario de $5000. A partir de la tercera semana, ese interés diario asciende a $7500.', time: '14:41', type: 'sent' },
        { sender: 'Tomás', content: 'Entiendo. Voy a hacer el pago la próxima semana.', time: '14:42', type: 'received' },
        { sender: 'Lucas', content: '¡Genial, Tomás!', time: '14:43', type: 'sent' },
        { sender: 'Lucas', content: 'No dudes en escribirme si necesitás que te envíe nuevamente los datos de pago o cualquier otra información.✅', time: '14:43', type: 'sent' },
        { sender: 'Lucas', content: 'Gracias por tu tiempo y por ser parte de nuestro plan de financiación. 🏡✨', time: '14:43', type: 'sent' }
      ],
      automotive: [
        { sender: 'Lucas', content: '¡Hola, Tomás! 😊 Quería recordarte que esta semana venció la cuota mensual de tu plan de ahorro.', time: '14:37', type: 'sent' },
        { sender: 'Lucas', content: '¿Tenés una fecha estimada en la que podrías realizar el pago?', time: '14:37', type: 'sent' },
        { sender: 'Tomás', content: 'No creo que pueda pagar esta semana. ¿Qué pasa si me atraso en el pago?', time: '14:38', type: 'received' },
        { sender: 'Lucas', content: 'Si realizás el pago dentro de la próxima semana, podemos hacer una excepción y no aplicar intereses por el atraso.', time: '14:39', type: 'sent' },
        { sender: 'Lucas', content: 'A partir de la segunda semana de vencimiento, sí se empiezan a aplicar intereses por mora.', time: '14:39', type: 'sent' },
        { sender: 'Lucas', content: 'Es decir, tenés hasta las 18hs del viernes de la semana siguiente, o se aplicarán intereses.', time: '14:39', type: 'sent' },
        { sender: 'Tomás', content: '¿De cuánto es la penalización?', time: '14:40', type: 'received' },
        { sender: 'Lucas', content: 'A partir de la segunda semana de vencimiento, aplica un interés diario de $5000. A partir de la tercera semana, ese interés diario asciende a $7500.', time: '14:41', type: 'sent' },
        { sender: 'Tomás', content: 'Entiendo. Voy a hacer el pago la próxima semana.', time: '14:42', type: 'received' },
        { sender: 'Lucas', content: '¡Genial, Tomás!', time: '14:43', type: 'sent' },
        { sender: 'Lucas', content: 'No dudes en escribirme si necesitas que te envíe nuevamente los datos de pago o cualquier otra información.✅', time: '14:43', type: 'sent' },
        { sender: 'Lucas', content: 'Gracias por tu tiempo y por ser parte de nuestro plan de ahorro. 🚗✨', time: '14:43', type: 'sent' }
      ],
      education: [
        { sender: 'Lucas', content: '¡Hola, Tomás! 😊 Quería recordarte que esta semana venció la cuota mensual de tu curso online de marketing avanzado.', time: '14:37', type: 'sent' },
        { sender: 'Lucas', content: <>Te comparto el link para que puedas pagar tu cuota mensual del curso: <a href="#" className="text-[#3A58ED] hover:underline" target="_blank" rel="noopener noreferrer">https://curso-marketing-online-avanzado.com/pagar-cuota-mensual</a></>, time: '14:37', type: 'sent' },
        { sender: 'Tomás', content: 'No creo que pueda pagar esta semana. ¿Qué pasa si me atraso en el pago?', time: '14:38', type: 'received' },
        { sender: 'Lucas', content: 'Si realizás el pago dentro de la próxima semana, podemos hacer una excepción y no aplicar intereses por el atraso.', time: '14:39', type: 'sent' },
        { sender: 'Lucas', content: 'A partir de la segunda semana de vencimiento, sí se empiezan a aplicar intereses por mora.', time: '14:39', type: 'sent' },
        { sender: 'Lucas', content: 'Es decir, tenés hasta las 18hs del viernes de la semana siguiente; de lo contrario, se aplicarán intereses.', time: '14:39', type: 'sent' },
        { sender: 'Tomás', content: '¿De cuánto es la penalización?', time: '14:40', type: 'received' },
        { sender: 'Lucas', content: 'A partir de la segunda semana de vencimiento, se aplica un interés diario de $5000. A partir de la tercera semana, ese interés diario asciende a $7500.', time: '14:41', type: 'sent' },
        { sender: 'Lucas', content: '¿Tenés una fecha estimada en la que podrías realizar el pago?', time: '14:41', type: 'sent' },
        { sender: 'Tomás', content: 'Entiendo. Voy a hacer el pago la próxima semana.', time: '14:42', type: 'received' },
        { sender: 'Lucas', content: 'Genial, Tomás!', time: '14:43', type: 'sent' },
        { sender: 'Lucas', content: 'No dudes en escribirme si necesitás los datos de pago nuevamente o cualquier otra información.✅', time: '14:43', type: 'sent' },
        { sender: 'Lucas', content: 'Gracias por tu tiempo y por ser parte de nuestro programa de formación. ¡Mucho éxito con tu curso!', time: '14:43', type: 'sent' }
      ],
      insurance: [
        { sender: 'Lucas', content: 'Hola, Tomás! Solo quería recordarte que esta semana venció tu pago mensual del seguro del auto. 🚗', time: '14:37', type: 'sent' },
        { sender: 'Lucas', content: <>Aquí tenés el link de pago para tu cuota mensual: <a href="#" className="text-[#3A58ED] hover:underline" target="_blank" rel="noopener noreferrer">https://www.seguro-del-auto.com/pagar-cuota-mensual</a></>, time: '14:37', type: 'sent' },
        { sender: 'Tomás', content: 'Creo que no voy a poder pagar esta semana. ¿Qué pasa si me atraso con el pago?', time: '14:38', type: 'received' },
        { sender: 'Lucas', content: 'Si realizás el pago dentro de la próxima semana, podemos hacer una excepción y no se aplicarán recargos por demora. ✅', time: '14:39', type: 'sent' },
        { sender: 'Lucas', content: 'A partir de la segunda semana de atraso, se empezarán a aplicar intereses.', time: '14:39', type: 'sent' },
        { sender: 'Lucas', content: 'Tenés tiempo hasta el próximo viernes a las 18 hs, después de eso se aplicarán intereses.', time: '14:39', type: 'sent' },
        { sender: 'Tomás', content: '¿Cuánto es la penalidad?', time: '14:40', type: 'received' },
        { sender: 'Lucas', content: 'A partir de la segunda semana de atraso, se aplicará un interés diario de $5000. Desde la tercera semana, ese interés sube a $7500 por día. 💰⚠️', time: '14:41', type: 'sent' },
        { sender: 'Lucas', content: '¿Tenés una fecha estimada para realizar el pago?', time: '14:41', type: 'sent' },
        { sender: 'Tomás', content: 'Entendido. Haré el pago la próxima semana.', time: '14:42', type: 'received' },
        { sender: 'Lucas', content: 'Perfecto, Tomás! Estaré atento. 😊', time: '14:43', type: 'sent' },
        { sender: 'Lucas', content: 'Si necesitás que te reenvíe los datos de pago o cualquier otra información, no dudes en escribirme.', time: '14:43', type: 'sent' },
        { sender: 'Lucas', content: 'Gracias por tu tiempo y por confiar en nosotros para asegurar tu auto. 🚗✨', time: '14:43', type: 'sent' }
      ],
      services: [
        { sender: 'Lucas', content: 'Hola, Tomás! Solo un recordatorio de que esta semana venció tu pago mensual por nuestro servicio de asesoría. 😊', time: '14:37', type: 'sent' },
        { sender: 'Lucas', content: <>Aquí está el enlace para completar tu pago: <a href="#" className="text-[#3A58ED] hover:underline" target="_blank" rel="noopener noreferrer">https://www.servicio-de-asesoria.com/pagar-cuota-mensual</a></>, time: '14:37', type: 'sent' },
        { sender: 'Tomás', content: 'Creo que no podré pagar esta semana. ¿Qué pasa si me atraso con el pago?', time: '14:38', type: 'received' },
        { sender: 'Lucas', content: 'Si realizás el pago dentro de la próxima semana, podemos hacer una excepción y no se aplicarán recargos por demora. ✅', time: '14:39', type: 'sent' },
        { sender: 'Lucas', content: 'Sin embargo, a partir de la segunda semana de atraso, comenzarán a aplicarse intereses por pago tardío.', time: '14:39', type: 'sent' },
        { sender: 'Lucas', content: 'Tenés tiempo hasta el próximo viernes a las 18 hs; después de eso se aplicarán intereses. ⚠️', time: '14:39', type: 'sent' },
        { sender: 'Tomás', content: '¿Cuánto es la penalidad?', time: '14:40', type: 'received' },
        { sender: 'Lucas', content: 'A partir de la segunda semana de atraso, se aplica un interés diario de $5000. Desde la tercera semana en adelante, ese interés aumenta a $7500 por día. 💰', time: '14:41', type: 'sent' },
        { sender: 'Lucas', content: '¿Tenés una fecha estimada para realizar el pago?', time: '14:41', type: 'sent' },
        { sender: 'Tomás', content: 'Entendido. Haré el pago la próxima semana.', time: '14:42', type: 'received' },
        { sender: 'Lucas', content: 'Perfecto, Tomás!', time: '14:43', type: 'sent' },
        { sender: 'Lucas', content: 'No dudes en escribirme si necesitás nuevamente los datos de pago o cualquier otra información.✅', time: '14:43', type: 'sent' },
        { sender: 'Lucas', content: 'Gracias por tu tiempo y por elegir nuestro servicio de asesoría. Que tengas un excelente día! ✨', time: '14:43', type: 'sent' }
      ],
      healthcare: [
        { sender: 'Lucas', content: '¡Hola, Tomás! Quería recordarte que esta semana venció la cuota mensual de tu plan de tratamiento dermatológico. 😊', time: '14:37', type: 'sent' },
        { sender: 'Lucas', content: <>Aquí te dejo el link para que puedas realizar el pago: <a href="#" className="text-[#3A58ED] hover:underline" target="_blank" rel="noopener noreferrer">https://www.tratamiento-dermatologico.com/pagar-cuota-mensual</a></>, time: '14:37', type: 'sent' },
        { sender: 'Tomás', content: 'Creo que no voy a poder pagar esta semana. ¿Qué pasa si me atraso con el pago?', time: '14:38', type: 'received' },
        { sender: 'Lucas', content: 'Si realizás el pago dentro de la próxima semana, podemos hacer una excepción y no aplicar recargos por demora. 👍', time: '14:39', type: 'sent' },
        { sender: 'Lucas', content: 'A partir de la segunda semana de atraso, se aplicarán intereses por pago tardío.', time: '14:39', type: 'sent' },
        { sender: 'Lucas', content: 'Tenés tiempo hasta el próximo viernes a las 18 hs para evitar penalidades.', time: '14:39', type: 'sent' },
        { sender: 'Tomás', content: '¿Cuánto es la penalidad?', time: '14:40', type: 'received' },
        { sender: 'Lucas', content: 'A partir de la segunda semana de atraso, se aplicará un interés diario de $5000. A partir de la tercera semana, ese monto aumenta a $7500 por día. ⚠️', time: '14:41', type: 'sent' },
        { sender: 'Lucas', content: '¿Tenés una fecha estimada para realizar el pago?', time: '14:41', type: 'sent' },
        { sender: 'Tomás', content: 'Entendido. Haré el pago la próxima semana.', time: '14:42', type: 'received' },
        { sender: 'Lucas', content: 'Perfecto, Tomás! Quedo atento. 😊', time: '14:43', type: 'sent' },
        { sender: 'Lucas', content: 'No dudes en escribirme si necesitás que te reenvíe los datos de pago o cualquier otra información.', time: '14:43', type: 'sent' },
        { sender: 'Lucas', content: 'Gracias por tu tiempo y por confiar en nuestro tratamiento. ¡Esperamos que te sea de gran ayuda! ✨', time: '14:43', type: 'sent' }
      ],
      retail: [
        { sender: 'Lucas', content: '¡Hola, Tomás! Quería recordarte que esta semana venció la cuota mensual de tu sillón. 🛋️', time: '14:37', type: 'sent' },
        { sender: 'Lucas', content: <>Aquí te dejo el link de pago para tu cuota mensual: <a href="#" className="text-[#3A58ED] hover:underline" target="_blank" rel="noopener noreferrer">https://www.negocio-de-sillon.com/pagar-cuota-mensual</a></>, time: '14:37', type: 'sent' },
        { sender: 'Tomás', content: 'Creo que no voy a poder pagar esta semana. ¿Qué pasa si me atraso con el pago?', time: '14:38', type: 'received' },
        { sender: 'Lucas', content: 'Si realizás el pago dentro de la próxima semana, no se aplicarán recargos por excepción. 😊', time: '14:39', type: 'sent' },
        { sender: 'Lucas', content: 'A partir de la segunda semana de atraso, se comenzarán a aplicar intereses. Tenés tiempo hasta el próximo viernes a las 18 hs para evitar penalidades.', time: '14:39', type: 'sent' },
        { sender: 'Tomás', content: '¿Cuánto es la penalidad?', time: '14:40', type: 'received' },
        { sender: 'Lucas', content: 'A partir de la segunda semana, se aplica un recargo diario de $5000. Desde la tercera semana en adelante, ese recargo sube a $7500 por día. ⚠️', time: '14:41', type: 'sent' },
        { sender: 'Tomás', content: 'Entendido. Haré el pago la próxima semana.', time: '14:42', type: 'received' },
        { sender: 'Lucas', content: 'Perfecto, Tomás!', time: '14:43', type: 'sent' },
        { sender: 'Lucas', content: 'Si necesitás que te reenvíe los datos de pago o cualquier otra información, escribime sin problema.✅', time: '14:43', type: 'sent' },
        { sender: 'Lucas', content: 'Gracias nuevamente por elegir nuestro sillón. Que lo disfrutes! 🛋️✨', time: '14:43', type: 'sent' }
      ]
    }
}